version: '3.3'
services:
  dbserver:
    image: postgres:17.2-alpine3.21
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: distribuida
      PG_DATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "c:/db-distribuida:/var/lib/postgresql/data"
    ports:
      - "54321:5432"
    expose:
      - 5432
  consul:
    image: consul:1.15.4
    command: |
      agent -dev
      -ui
      -bind 0.0.0.0
      -client 0.0.0.0
    ports:
      - "8500:8500"
    expose:
      - 8500
  proxy:
    image: traefik:v3.3.1
    command: |
      --api.insecure=true
      --providers.consulCatalog
      --providers.consulCatalog.exposedByDefault=false
      --providers.consulCatalog.refreshInterval=5s
      --providers.consulCatalog.endpoint.address=consul:8500
      --providers.docker
      --providers.docker.exposedByDefault=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
      - "80:80"
    expose:
      - 80
    depends_on:
      - consul
  authors:
    image: willan98/app_authors:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rapp-authors.rule=PathPrefix(`/app-authors1`)"
      - "traefik.http.routers.rapp-authors.middlewares=mauthors"
      - "traefik.http.middlewares.mauthors.stripPrefix.prefixes=/app-authors1"
    environment:
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: postgres
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://dbserver:5432/distribuida
      QUARKUS_HTTP_PORT: 8080
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
    expose:
        - 8080
    depends_on:
      - dbserver
      - consul
    deploy:
        replicas: 1
  books:
    image: willan98/app_books:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rapp-books.rule=PathPrefix(`/app-books1`)"
      - "traefik.http.routers.rapp-books.middlewares=mbooks"
      - "traefik.http.middlewares.mbooks.stripPrefix.prefixes=/app-books1"
    environment:
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: postgres
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://dbserver:5432/distribuida
      QUARKUS_HTTP_PORT: 8080
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
    expose:
      - 8080
    depends_on:
      - dbserver
      - consul
      - authors