  #docker compose -f docker-compose-tracing-gateway.yml up -d
version: '3.3'
services:
  dbserver:
    image: postgres:17.2-alpine3.21
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: distribuida
      PG_DATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "c:/db-distribuida:/var/lib/postgresql/data"
    ports:
      - "54321:5432"
    expose:
      - 5432
  consul:
    image: consul:1.15.4
    command: |
      agent -dev
      -ui
      -bind 0.0.0.0
      -client 0.0.0.0
    ports:
      - "8500:8500"
    expose:
      - 8500
  proxy:
    image: traefik:v3.3.1
    command: |
      --api.insecure=true
      --providers.consulCatalog
      --providers.consulCatalog.exposedByDefault=false
      --providers.consulCatalog.refreshInterval=5s
      --providers.consulCatalog.endpoint.address=consul:8500
      --providers.docker
      --providers.docker.exposedByDefault=false
      --tracing=true
      --tracing.addinternals=false
      --tracing.otlp=true
      --tracing.otlp.http=true
      --tracing.otlp.http.endpoint=http://jeager:4318

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
      #- "8082:8082"
      - "80:80"
    expose:
      - 80
    depends_on:
      - consul

  jeager:
    image: jaegertracing/jaeger:2.2.0
    ports:
      - "16686:16686" #UI
      - "4317:4317"   #gRPC
      - "4318:4318"   #HTTP
    expose:
      - 16686
      - 4317
      - 4318
    depends_on:
      - proxy
  authors:
    image: willan98/app_authors:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rapp-authors.rule=PathPrefix(`/app-authors1`)"
      - "traefik.http.routers.rapp-authors.middlewares=mauthors"
      - "traefik.http.middlewares.mauthors.stripPrefix.prefixes=/app-authors1"
    environment:
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: postgres
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://dbserver:5432/distribuida
      QUARKUS_HTTP_PORT: 8080
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
      QUARKUS_HIBERNATE-ORM_METRICS_ENABLED: true
      QUARKUS_OTEL_EXPORTER_OTLP_ENDPOINT: http://jeager:4317

    expose:
      - 8080
    depends_on:
      - dbserver
      - consul
    deploy:
      replicas: 1
  books:
    image: willan98/app_books:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rapp-books.rule=PathPrefix(`/app-books1`)"
      - "traefik.http.routers.rapp-books.middlewares=mbooks"
      - "traefik.http.middlewares.mbooks.stripPrefix.prefixes=/app-books1"
    environment:
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: postgres
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://dbserver:5432/distribuida
      QUARKUS_HTTP_PORT: 8080
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
      QUARKUS_HIBERNATE-ORM_METRICS_ENABLED: true
      QUARKUS_OTEL_EXPORTER_OTLP_ENDPOINT: http://jeager:4317
      QUARKUS_HTTP_CORS: true
      QUARKUS_HTTP_CORS_ORIGINS: /.*/
      QUARKUS_HTTP_CORS_METHODS: GET,PUT,POST,DELETE
      QUARKUS_HTTP_CORS_HEADERS: X-Custom
      QUARKUS_HTTP_CORS_EXPOSED_HEADERS: Content-Disposition
    expose:
      - 8080
    depends_on:
      - dbserver
      - consul
      - authors
    deploy:
        replicas: 2