apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-vue
  labels:
    app: app-vue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-vue
  template:
    metadata:
      name: app-vue
      labels:
        app: app-vue
    spec:
      containers:
        - name: app-vue
          image: docker.io/willan98/app_vue:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
          env:
            - name: VUE_APP_HOST
              value: app-books-services
            - name: VUE_APP_PORT
              value: "3001"
            - name: VUE_APP_PATH
              value: "books"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: app-vue-service
spec:
  type: LoadBalancer
  selector:
    app: app-vue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: app-vue-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-vue
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50