apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-authors
  labels:
    app: app-authors
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-authors
  template:
    metadata:
      name: app-authors
      labels:
        app: app-authors
    spec:
      containers:
        - name: app-authors
          image: docker.io/willan98/app_authors:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: JAVAX_SQL_DATASOURCE_DS1_SERVER_NAME
              value: 127.0.0.1
            - name: JAVAX_SQL_DATASOURCE_DS1_DATABASE_NAME
              value: distribuida
            - name: JAVAX_SQL_DATASOURCE_DS1_PORT_NUMBER
              value: "5432"
            - name: JAVAX_SQL_DATASOURCE_DS1_USER
              value: postgres
            - name: JAVAX_SQL_DATASOURCE_DS1_PASSWORD
              value: rc2ijxxz
            - name: SERVER_PORT
              value: "8080"
            - name: CONSUL_HOST
              value: "consul"
            - name: CONSUL_PORT
              value: "8500"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: app-authors-service
  labels:
      app: app-authors
spec:
    type: ClusterIP
    selector:
        app: app-authors
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: app-authors-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-authors
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 50