global:
    scrape_interval: 5s
    evaluation_interval: 5s

scrape_configs:
#  - job_name: 'authors-app'
#    scrape_interval: 10s
#    metrics_path: '/q/metrics'
#    static_configs:
#      - targets: ['authors:8080']
#  - job_name: postgres
#    static_configs:
#      - targets: [ 'postgres-exporter:9187' ]
#  - job_name: 'books-app'
#    scrape_interval: 10s
#    metrics_path: '/q/metrics'
#    static_configs:
#      - targets: ['books:8081']
  - job_name: 'proxy'
    static_configs:
      - targets: ['proxy:8082']